sudo: false
language: node_js
node_js:
  - node # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
before_script:
  - git clone theme git@github.com:tim621/tim612.github.io.git themes/Volantis
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public # 生成静态网页

 # 构建完成之后的操作
after_script:
  - cd ./public # 进入静态资源目录
  - git init # 初始化仓库
  - git config user.name "tim612" # 设置用户名
  - git config user.email "647827157@qq.com" # 设置邮箱
  - git add . # 添加所以文件到缓冲区
  - git commit -m "Auto deploy blog pages" # 备注
  - git push --force --quiet "https://${GH_TOKEN}@github.com//tim612.github.io" master:master

branches:
  only:
    - source

cece