sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
script:
  - hexo generate # generate static files
deploy:
  provider: pages
   ocal_dir: public/
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch:  source
  local-dir: publicocal-dir: publicnch:  source
  local-dir: publicocal-dir: public