language: node_js # 语言环境

node_js: node #稳定版

# 安装依赖，Travis CI modejs环境默认有配置，写不写无所谓
# install:
#   - npm install

# 构建前阶段
before_script:
  - git clone -b theme git@github.com:tim621/tim612.github.io.git#克隆主题到虚拟机

# 构建阶段
script:
  - hexo clean # 我认为多此一举，Travis好像并不保存数据
  - hexo generate # 生成静态网页

 # 构建完成之后的操作
after_script:
  - cd ./public # 进入静态资源目录
  - git init # 初始化仓库
  - git config user.name "tim612" # 设置用户名
  - git config user.email "647827157@qq.com" # 设置邮箱
  - git add . # 添加所以文件到缓冲区
  - git commit -m "Auto deploy blog pages" # 备注
  - git push --force --quiet "https://${GH_TOKEN}@github.com//tim612.github.io" master:master

branches:
  only:
    - sourceurcece